# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4cbd32776b53759aa5be44d94dfbbb44231b037e8b7ff78956ae6f0fabb155082b3246e305595fb9966360f96020aa4cbd45a89fd65de1ff6efc4c7e89117d26

test:
  secret_key_base: f8b074e5a758e496741ddf4ef024327f8a1379b85e0ccffc5cfeb69d36a840d43c68b766b20dd35246cb6d7cd27d8e9cebcd873df20131645b4d5fa7bd889c5b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
